[mypy]
python_version = 3.11
; Check untyped function definitions
check_untyped_defs = True
; Disallow untyped function definitions
disallow_untyped_defs = True
; Warn about functions returning Any
warn_return_any = True
; Warn about unused configs
warn_unused_configs = True

; Ignore third-party library type checks
[mypy-alibabacloud_oss_v2.*]
ignore_missing_imports = True

[mypy-alibabacloud_oss_v2]
ignore_missing_imports = True

; Other ignore rules
[mypy-boto3.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True